// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __DataService_hh__
#define __DataService_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_DataService
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_DataService
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_DataService
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __DataService__
#define __DataService__

class DataService;
class _objref_DataService;
class _impl_DataService;

typedef _objref_DataService* DataService_ptr;
typedef DataService_ptr DataServiceRef;

class DataService_Helper {
public:
  typedef DataService_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_DataService, DataService_Helper> DataService_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_DataService,DataService_Helper > DataService_out;

#endif

// interface DataService
class DataService {
public:
  // Declarations for this interface type.
  typedef DataService_ptr _ptr_type;
  typedef DataService_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_DataService :
  public virtual CORBA::Object,
  public virtual omniObjRef
{
public:
  void insert(const char* stuName, const char* StuNo, CORBA::Float score);
  CORBA::Float search(const char* stuNo);

  inline _objref_DataService()  { _PR_setobj(0); }  // nil
  _objref_DataService(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_DataService();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_DataService(const _objref_DataService&);
  _objref_DataService& operator = (const _objref_DataService&);
  // not implemented

  friend class DataService;
};

class _pof_DataService : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_DataService() : _OMNI_NS(proxyObjectFactory)(DataService::_PD_repoId) {}
  virtual ~_pof_DataService();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_DataService :
  public virtual omniServant
{
public:
  virtual ~_impl_DataService();

  virtual void insert(const char* stuName, const char* StuNo, CORBA::Float score) = 0;
  virtual CORBA::Float search(const char* stuNo) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_DataService :
  public virtual _impl_DataService,
  public virtual PortableServer::ServantBase
{
public:
  virtual ~POA_DataService();

  inline ::DataService_ptr _this() {
    return (::DataService_ptr) _do_this(::DataService::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
DataService::_marshalObjRef(::DataService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_DataService
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_DataService
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_DataService
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_DataService
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_DataService
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_DataService
#endif

#endif  // __DataService_hh__

